export const ADD_FAVORITES_DATA = 'ADD_FAVORITES_DATA';
export const DELETE_FAVORITES_DATA = 'DELETE_FAVORITES_DATA';
export const REQUEST_FAVORITES_DATA = 'REQUEST_FAVORITES_DATA';
export const RECEIVES_FAVORITES_DATA = 'RECEIVES_FAVORITES_DATA';
export const FAILURE_FAVORITES_DATA = 'FAILURE_FAVORITES_DATA';