export const REQUEST_SONGS_DATA = 'REQUEST_SONGS_DATA';
export const RECEIVE_SONGS_DATA = 'RECEIVE_SONGS_DATA';
export const RECEIVE_SONGS_DATA_WITH_SEARCH = 'RECEIVE_SONGS_DATA_WITH_SEARCH';
export const FAILURE_SONGS_DATA = 'FAILURE_SONGS_DATA';